server:
  port: 80

spring:
  application:
    name: ProjectBajeet
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET_ID}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET_ID}
            scope:
              - user:email
              - read:user

gg:
  jte:
    developmentMode: true

logging:
  level:
    org:
      springframework:
        security: ERROR #change to DEBUG or INFO for more information about spring security