server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projectbajeet
    username: postgres
    password: qovpoh-2naxze-Pivkuj
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_nationalized_character_data: true
        enable_lazy_load_no_trans: true
  application:
    name: ProjectBajeet
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET_ID}
            redirect-uri: https://projectbajeet.work.gd/api/oauth2/code/google
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET_ID}
            redirect-uri: https://projectbajeet.work.gd/api/oauth2/code/github
            scope:
              - user:email
              - read:user

gg:
  jte:
    developmentMode: true
